config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'registrations' }
  root to: 'pages#home'

  resources :experiences
  resources :users, only: [:show]
  resources :events do
    resources :bookings, except: [ :index ] do
    resources :payments, only: [:new, :create]
    get '/denial', to: 'bookings#update_denial'
    patch '/denial', to: 'bookings#update_denial'
     end
    resources :reviews, only: [ :show, :new, :create, :destroy ]

  end

  resources :conversations do
    resources :messages
  end


  get '/profile', to: 'pages#profile'
  get '/dashboard', to: 'events#dashboard'
  as :user do
    get 'users', to: 'pages#profile', as: :user_root # Rails 3
  end


  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer footermain site-footer">
  <div class="footer-copyright">
    <%= image_tag "logo_footer.png", height: 50, class: "footer-logo" %>
    <strong>©</strong> Travel. Meet. Play. (2018)
  </div>
  <div>
    <div class="footer-links">
      <a href="https://www.instagram.com/travelmeetplay/" target="_blank" class="footlinks"><i class="fab fa-instagram"></i></a>
      <a href="https://www.facebook.com/Travel-Meet-Play-182421305869840/" target="
      _blank" class="footlinks"><i class="fab fa-facebook"></i></a>
      <a href="https://twitter.com/travelmeetplay" target="
      _blank" class="footlinks"><i class="fab fa-twitter"></i></a>
      <a href="https://en.hubtokyo.com/" target="
      _blank" class="footlinks"><i class="fas fa-location-arrow"></i></a>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to events_path, class: "navbar-logo" do %>
    <%= image_tag "logo_navbar.png", height: 50 %>
  <% end %>
  <div class="navbar-wagon-right hidden-xs hidden-sm">
      <div class="search-container form-inline">
        <%= form_tag events_path, method: :get do %>
          <%= text_field_tag :search,
            params[:search],
            class: "form-control search-bar",
            placeholder: "Type a sport or location" %>
          <%= button_tag class: "btn-primary btn-search" do %>
            <i class="fas fa-search"></i>
          <% end %>
        <% end %>
      </div>

    <% if user_signed_in? %>

      <!-- Links when logged in -->
    <div class="dropdown">
      <%= link_to "My Events", dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %>
     <div class="dropdown-content">
      <%= link_to "New Event", new_event_path,  class: "navbar-wagon-item navbar-wagon-link" %>
       </div>
      </div>

      <%= link_to "Messages", conversations_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Profile", profile_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
    <% else %>
        <!-- Login link (when logged out) -->
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>

      <div class="dropdown">
          <% if @user.present? %>
            <% if @user.photo.present? %>
              <%= cl_image_tag (@user.photo), class: "avatar-picture" %>
            <% end %>
          <% end %>
        <div class="dropdown-content">

           <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>
        </div>
      </div>



    <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Profile", profile_path %></li>
          <li><%= link_to "Events", events_path %></li>
          <li><%= link_to "Messages", conversations_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
    </div>
  </div>
</div>