config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'registrations' }
  root to: 'pages#home'

  resources :experiences
  resources :users, only: [:show]
  resources :events do
    resources :bookings, except: [ :index ] do
    resources :payments, only: [:new, :create]
    get '/denial', to: 'bookings#update_denial'
    patch '/denial', to: 'bookings#update_denial'
     end
    resources :reviews, only: [ :show, :new, :create, :destroy ]

  end

  resources :conversations do
    resources :messages
  end


  get '/profile', to: 'pages#profile'
  get '/dashboard', to: 'events#dashboard'
  as :user do
    get 'users', to: 'pages#profile', as: :user_root # Rails 3
  end


  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :sport
  belongs_to :host, class_name: "User"

  include PgSearch
  pg_search_scope :search_full_text,
    against: [ :address ],
    associated_against: {
      sport: [ :name ]
    },
    using: {
      tsearch: { prefix: true },
    },
    order_within_rank: "events.updated_at DESC"

  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy

  monetize :price_cents

  validates :date, presence: true
  validates :max_players, presence: true

  def nice_date
    date.strftime("%b %d, %Y") if date
  end

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def spots_left
      max_players - bookings.where(status: "approved").count
  end

  def is_user_registered?(user)
    !bookings.where(user_id: user.id).blank?
  end

  def booking_pending?(user)
    bookings.exists?(user_id: user.id, status: "pending")
  end

  def booking_approved?(user)
    bookings.exists?(user_id: user.id, status: "approved")
  end

  def booking_rejected?(user)
    bookings.exists?(user_id: user.id, status: "rejected")
  end

  # def conversation_with(user)
  #   if Conversation.between(@event.host.id, current_user.id).present?
  #     @conversation = Conversation.between(@event.host.id, current_user.id).first
  #   else
  #    @conversation = Conversation.create!(recipient_id: @event.host.id, sender_id: current_user.id)
  #   end
  # end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [ :show, :edit, :destroy, :update, :delete ]

  def index
    @user = current_user
    @events = policy_scope(Event)
    # @events = Event.all

    if params[:search].present?
      @events = Event.search_full_text(params[:search])


            #   sql_query = " \
    #     events.address ILIKE :search \
    #     OR sports.name ILIKE :search \
    #   "
    #   @events = Event.joins(:sport).where(sql_query, search: "%#{params[:search]}%")
    else
       @events = policy_scope(Event)
    end

    @markers = @events.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude,
        infoWindow: { content: render_to_string(partial: "/events/map_box", locals: { event: event }) }
      }
    end
  end

  def show
    @user = current_user
    authorize @event
  end

  def dashboard
    @user = @host = current_user
    @events = current_user.events
    @bookings = current_user.bookings
    @reviews = current_user.reviews
    authorize @events
    authorize @bookings
  end

  def new
    @event = Event.new
    authorize @event
    @user = current_user
  end

  def create
    @event = Event.new(event_params)
    @event.host = current_user
    @event.spots_left = @event.max_players
    if @event.save
      redirect_to dashboard_path
    else
      render :new
    end
    authorize @event
  end

  def edit
    @user = current_user
    authorize @event
  end

  def update
    @event.update(
      address: params[:event][:address],
      date: params[:event][:date],
      max_players: params[:event][:max_players],
      price: params[:event][:price],
      description: params[:event][:description]
      )
    authorize @event
    redirect_to event_path
  end

  def destroy
    @event.destroy
    authorize @event
    redirect_to dashboard_path
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:address, :date, :max_players, :host_id, :sport_id, :price, :description)
  end
end

app/views/events/_event_registered_players.html.erb
<div class="col-xs-6">
  <h3>Registered players </h3>
  <% if @event.bookings.where(status: "approved").blank? %>
    <p>There are no players registered for this event yet.</p>
  <% else %>
    <% @event.bookings.each do |booking| %>
    <% if @event.booking_approved?(booking.user) %>
      <%  if booking.user.first_name %>
        <p><%= image_tag ("#{@event.sport.name.downcase}.png"), class: "event-logo" %> <%= booking.user.first_name %>
          <% if booking.user.country_name %>
          from <%= booking.user.country_name %></p>
        </p>
          <% end %>
      <% end %>
    <% end  %>
    <% end  %>
  <% end %>

    <% if @event.date < Date.today %>
      <p> This event has already occured.</p>
    <% elsif @event.host.id == current_user.id %>
      <p>This is an event you created.</p>
    <% elsif @event.bookings.blank? %>
      <p>Be the first one to do so below:</p>
      <%= button_to "Register", event_bookings_url(@event), class: "btn btn-primary"%>

    <% elsif @event.spots_left > 0 && !@event.is_user_registered?(current_user) %>
      <p>Register for this event below: </p>
      <%= button_to "Register", event_bookings_url(@event), class: "btn btn-primary"%>

    <% elsif @event.booking_pending?(current_user) %>
      <p>Your registration is currently pending. The host is setting up the event and will get back to you shortly.</p>
    <% elsif @event.booking_approved?(current_user) %>
      <p> Your booking has been approved! You will be participating in this event.</p>
    <% elsif @event.booking_rejected?(current_user) %>
      <p> Unfortunately, your booking has been rejected... We invite you to find another event in your area. </p>
    <% else  %>
      <p>This event is currently full. We will notify you if spots become available.</p>
  <% end %>
</div>

app/views/events/_event_sport_status.html.erb
<div class="col-xs-6">
  <div>
    <h3>
      <%= image_tag "#{@event.sport.name.downcase}.png", class: "event-main-images" %> <strong><%= @event.sport.name %></strong> on <strong><%= @event.nice_date %></strong>
    </h3>
    <div>
      <h4>
        <% unless @event.host.id == current_user.id %>
          <% if @event.host.photo.present? %>
            <%= cl_image_tag @event.host.photo, class: "event-main-images event-host" %>
          <% end %>
          <%= @event.host.first_name %>
          <%= link_to user_path(@event.host.id) do %>
            <i class="far fa-user"></i>
          <% end %>
          <%= link_to conversation_messages_path(@event.host.conversation_with(current_user)) do %>
            <i class="far fa-envelope"></i>
          <% end %>
        <% end %>
      </h4>
    </div>
    <br>
  </div>
  <div>
    <p>Spots available:
      <% if (@event.max_players - @event.spots_left) == 0 %>
        <% @event.max_players.times do %>
          <i class="fas fa-male spots"></i>
          <% end %>
      <% else %>
        <% @event.spots_left.times do %>
          <i class="fas fa-male spots"></i>
        <% end %>
        <% (@event.max_players - @event.spots_left).times do %>
          <i class="fas fa-male spots-taken"></i>
        <% end %>
      <% end %>
      (<%= @event.spots_left %>/<%= @event.max_players %>)
    </p>
  </div>
  <div>
    <p>Event description: <%= @event.description %></p>
  </div>
</div>

app/views/events/_map_box.html.erb
<%= image_tag ("#{event.sport.name.downcase}.png"), class: "map-logo" %>

<%= link_to event_path(event) do %>
  <%= event.sport.name %>
  <%= event.nice_date %></p>
<% end %>

<p>There are <%= event.spots_left %> spots left</p>

app/views/events/_my_booked_events.html.erb
<div class="col-lg-6">
  <div class="my_titles">
  <h3>Your bookings</h3>
  <hr>
  </div>
  <div class="row">
    <% @bookings.each do |booking| %>
      <div class="row boxer card_fonts">
        <h4><%= image_tag "#{booking.event.sport.name.downcase}.png", class: "event-main-images" %> <%= link_to booking.event.sport.name + " on " + booking.event.nice_date, event_path(booking.event), class: "card_fonts" %></h4>
        <p>
          <% if booking.event.host.photo.present? %>
            <%= cl_image_tag (booking.event.host.photo), class: "event-owner" %>
          <% end %>
          Hosted by
          <strong><%= link_to booking.event.host.first_name, user_path(booking.event.host.id) %></strong>
        </p>
        <p>
          <i class="fas fa-map-marker-alt"></i>
          <%= booking.event.address %>
        </p>
        <p>
          <strong>Status:</strong> <%= booking.status.capitalize %>
        </p>
        <p>
          <% unless booking.event.date < Date.today %>
            <%= link_to event_booking_path(booking.event, booking), :method => :delete, data: {:confirm => "Are you sure you want to cancel your booking for this event?" } do %>
            <i class="fas fa-times"></i>
            <% end %>
            Cancel booking
          <% end %>
        </p>

        <% if booking.event.date < Date.today %>
          <p><strong>Reviews for this event:</strong><br>
            <% booking.event.reviews.each do |review| %>
              <p class="review-components">Rating:
                <% review.rating.to_i.times do %>
                  <i class="fas fa-star positive-review"></i>
                <% end %>
                <% (5 - review.rating.to_i).times do %>
                  <i class="fas fa-star no-review"></i>
                <% end %>
              (<%= review.rating.to_i %>/5)
              by
              <%= review.user.first_name %>
            </p>
            <% end %>
          </p>

          <% unless booking.event.reviews.where(user: current_user).exists? %>
            <% review = booking.event.reviews.new %>
            <%= simple_form_for review, url: event_reviews_path(booking.event) do |f| %>
              <div class="form-inline">
                <%= f.input :rating, as: :radio_buttons, collection: [1, 2, 3, 4, 5], input_html: {class: "radios"} %>
              </div>
              <%= f.input :review_content %>
              <%= button_tag class: "btn-primary navbar-button" do %>
                <i class="far fa-save"></i>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/_my_created_events.html.erb
<div class="col-lg-6">
  <div class="my_titles">
    <h3>Events you have created</h3>
    <hr>
  </div>
  <p class="new_event">
    <%= link_to new_event_url do %>
      <i class="fas fa-plus"></i>
    <% end %>
    Create new event
  </p>
  <div class="row separator">
    <% @events.each do |event| %>
      <div class="row boxer card_fonts">
        <h4><%= image_tag "#{event.sport.name.downcase}.png", class: "event-main-images" %> <%= link_to event.sport.name + " on " + event.nice_date, event_path(event), class: "card_fonts" %></h4>
        <p>
          <i class="fas fa-map-marker-alt"></i>
          <%= event.address %>
        </p>
        <% event.bookings.each do |booking| %>
          <p><%= link_to booking.user.first_name, user_path(booking.user.id) %> has registered. Booking: <%= booking.status.capitalize %></p>
          <% if booking.status == "pending" %>
            <p>
              <%= link_to event_booking_path(event, booking), method: :patch do%>
              <i class="fas fa-check"></i>
              <% end %>
              Approve
              <%= link_to event_booking_denial_path(event, booking), method: :patch do%>
              <i class="fas fa-times"></i>
              <% end %>
              Reject
            </p>
            <p>
            </p>
          <% end %>
        <% end %>
        <% if event.reviews.count > 0 %>
          <p><strong>Reviews for this event:</strong></p>
          <% event.reviews.each do |review| %>
            <div class="review-box">
              <p class="review-components">Rating:
                <% review.rating.to_i.times do %>
                  <i class="fas fa-star positive-review"></i>
                <% end %>
                <% (5 - review.rating.to_i).times do %>
                  <i class="fas fa-star no-review"></i>
                <% end %>
                (<%= review.rating.to_i %>/5)
              </p>
              <p class="review-components">Comment: <%= review.review_content %></p>
            </div>
          <% end %>
        <% end %>
        <div class="event-links">
          <p>
            <%= link_to edit_event_path(event) do %>
              <i class="far fa-edit"></i>
            <% end %>
            <%= link_to event_path(event), :method => :delete, data: {:confirm => "Are you sure you want to delete this event?" } do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/dashboard.html.erb
<div class="container">
  <div class="row">
    <%= render 'my_created_events' %>
    <%= render 'my_booked_events' %>
  </div>
</div>

app/views/events/edit.html.erb
   <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <h1>Edit your <%= @event.sport.name %> game</h1>

        <%= simple_form_for @event do |f| %>
          <%= f.association :sport %>
          <%= f.input :address, id: "eventAddress" %>
            <p>Date</p>
             <%= f.input_field :date,  label: "Date", as: :string, class: 'datetimepicker' %>
          <%= f.input :description %>
          <%= f.input :max_players %>
          <%= f.input :price, label: 'Participant fee per person (in Japanese Yen)' %>
          <%= f.button :submit, "Edit event", class: "add-skill-button" %>
        <% end %>
        </div>
     </div>
  </div>

app/views/events/index.html.erb
<div class="container">
  <div class="home">
    <div class="row all-cards">
      <div class="col-xs-8 col-sm-8 col-lg-8 col-xl-8">
        <h3>Hi <%= @user.first_name %>! Here's what's happening around you</h3>
        <hr>
        <% @events.order(:date).each do |event| %>
        <% unless event.date < Date.today %>
          <%= link_to event_path(event) do %>
            <div class="card col-xs-4 col-sm-4 col-lg-4">
              <div>
                <%= image_tag ("#{event.sport.name.downcase}.png"), class: "card-photo" %>
              </div>
              <div class="booking-content">
                <h4><%= event.sport.name %></h4>
                <p><i class="fas fa-map-marker-alt"></i> <%= event.address %></p>
                <p>By <%= event.host.first_name %></p>
                <p><%= event.nice_date %></p>
              </div>
            </div>
          <% end %>
         <% end %>
        <% end %>
      </div>
      <div class="col-xs-4 col-sm-4 col-lg-4 col-xl-4 mapper">
        <div
          id="map"
          style="width: 100%;
          position: sticky;
          height: 90vh;
          margin: 10px;"
          data-markers="<%= @markers.to_json %>">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <h1>Create a new game!</h1>

        <%= simple_form_for @event do |f| %>
          <%= f.association :sport %>
          <%= f.input :address, id: "eventAddress" %>
             <%= f.label :date %>
             <%= f.input_field :date,  label: "Date", as: :string, class: 'datetimepicker' %>
          <%= f.input :max_players %>
          <%= f.input :description %>
          <%= f.input :price, label: 'Participant fee per person (in Japanese Yen)' %>
          <%= f.button :submit, "Create event", class: "add-skill-button" %>
        <% end %>
        </div>
     </div>
  </div>

app/views/events/show.html.erb
<div class="container">
  <div class="row boxer">
    <%= render 'event_sport_status' %>
    <%= render 'event_registered_players' %>
  </div>
</div>