config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'registrations' }
  root to: 'pages#home'

  resources :experiences
  resources :users, only: [:show]
  resources :events do
    resources :bookings, except: [ :index ] do
    resources :payments, only: [:new, :create]
    get '/denial', to: 'bookings#update_denial'
    patch '/denial', to: 'bookings#update_denial'
     end
    resources :reviews, only: [ :show, :new, :create, :destroy ]

  end

  resources :conversations do
    resources :messages
  end


  get '/profile', to: 'pages#profile'
  get '/dashboard', to: 'events#dashboard'
  as :user do
    get 'users', to: 'pages#profile', as: :user_root # Rails 3
  end


  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    before_action :set_order

  def new
    authorize @booking
  end

  def create
    authorize @booking
    flash[:notice] = "Confirmation request has been sent to the event owner"
    redirect_to dashboard_path
  end

private

  def set_order
    @event = Event.find(params[:event_id])
    @booking = Booking.where(status: 'pending').find(params[:booking_id])
  end
end

app/views/payments/new.html.erb
<div class="container">
  <div class="row">
    <%= form_tag event_booking_payments_path(@event, @booking) do %>
    <div class="col-sm-6 col-sm-offset-3" align="center">
      <h3>Booking Confirmation</h3>
      <h4>
        <%= image_tag "#{@booking.event.sport.name.downcase}.png", class: "event-main-images" %> <strong><%= @booking.event.sport.name %></strong> with <%= @booking.event.host.first_name %>
        <% if @user.present? %>
          <% if @user.photo.present? %>
            <%= cl_image_tag @event.host.photo, class: "event-main-images event-host" %>
          <% end %>
        <% end %>
      </h4>
      <label>
        <span> Participation fee:
        <%= humanized_money_with_symbol(@booking.amount) %></span>
      </label>

    </div>
    <br>
    <br>
    <div class="col-sm-6 col-sm-offset-3" align="center">
      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-name="<%= @booking.event.sport.name %>"
        data-email="<%= current_user.email %>"
        data-description="with <%= @booking.event.host.first_name %>"
        data-amount="<%= @booking.amount_cents %>"
        data-currency="<%= @booking.amount.currency %>">
      </script>
    </div>
  <% end %>
  </div>
</div>